spring.application.name=project
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop
spring.config.import=optional:file:.env[.env]

logging.level.org.springframework.web.client.RestTemplate=DEBUG

jwt.secret=${JWT_SECRET}
jwt.expiration-access=${JWT_EXPIRATION_ACCESS}
jwt.expiration-refresh=${JWT_EXPIRATION_REFRESH}
